# Makefile generated by MakefileGenerator.cs
# *DO NOT EDIT*

UNREALROOTPATH = /mnt/SSD870/UnrealEngine/5.3.2
GAMEPROJECTFILE =/home/madmonki/EVO870/unrealprojs/DoomsDay/DoomsDayge.uproject

TARGETS = \
	DoomsDayge-Linux-DebugGame  \
	DoomsDayge-Linux-Shipping  \
	DoomsDayge \
	DoomsDaygeEditor-Linux-DebugGame  \
	DoomsDaygeEditor-Linux-Shipping  \
	DoomsDaygeEditor \
	UnrealEditor-Linux-DebugGame  \
	UnrealEditor-Linux-Shipping  \
	UnrealEditor \
	UnrealGame-Linux-DebugGame  \
	UnrealGame-Linux-Shipping  \
	UnrealGame\
	configure

BUILD = bash "$(UNREALROOTPATH)/Engine/Build/BatchFiles/Linux/Build.sh"
PROJECTBUILD = "$(UNREALROOTPATH)/Engine/Binaries/ThirdParty/DotNet/6.0.302/linux/dotnet" "$(UNREALROOTPATH)/Engine/Binaries/DotNET/UnrealBuildTool/UnrealBuildTool.dll"

all: StandardSet

RequiredTools: CrashReportClient-Linux-Shipping CrashReportClientEditor-Linux-Shipping ShaderCompileWorker UnrealLightmass EpicWebHelper-Linux-Shipping

StandardSet: RequiredTools UnrealFrontend DoomsDaygeEditor UnrealInsights

DebugSet: RequiredTools UnrealFrontend-Linux-Debug DoomsDaygeEditor-Linux-Debug


DoomsDayge-Linux-DebugGame:
	 $(PROJECTBUILD) DoomsDayge Linux DebugGame  -project="$(GAMEPROJECTFILE)" $(ARGS)

DoomsDayge-Linux-Shipping:
	 $(PROJECTBUILD) DoomsDayge Linux Shipping  -project="$(GAMEPROJECTFILE)" $(ARGS)

DoomsDayge:
	 $(PROJECTBUILD) DoomsDayge Linux Development  -project="$(GAMEPROJECTFILE)" $(ARGS)

DoomsDaygeEditor-Linux-DebugGame:
	 $(PROJECTBUILD) DoomsDaygeEditor Linux DebugGame  -project="$(GAMEPROJECTFILE)" $(ARGS)

DoomsDaygeEditor-Linux-Shipping:
	 $(PROJECTBUILD) DoomsDaygeEditor Linux Shipping  -project="$(GAMEPROJECTFILE)" $(ARGS)

DoomsDaygeEditor:
	 $(PROJECTBUILD) DoomsDaygeEditor Linux Development  -project="$(GAMEPROJECTFILE)" $(ARGS)

UnrealEditor-Linux-DebugGame:
	 $(BUILD) UnrealEditor Linux DebugGame  -project="$(GAMEPROJECTFILE)" $(ARGS)

UnrealEditor-Linux-Shipping:
	 $(BUILD) UnrealEditor Linux Shipping  -project="$(GAMEPROJECTFILE)" $(ARGS)

UnrealEditor:
	 $(BUILD) UnrealEditor Linux Development  -project="$(GAMEPROJECTFILE)" $(ARGS)

UnrealGame-Linux-DebugGame:
	 $(BUILD) UnrealGame Linux DebugGame  -project="$(GAMEPROJECTFILE)" $(ARGS)

UnrealGame-Linux-Shipping:
	 $(BUILD) UnrealGame Linux Shipping  -project="$(GAMEPROJECTFILE)" $(ARGS)

UnrealGame:
	 $(BUILD) UnrealGame Linux Development  -project="$(GAMEPROJECTFILE)" $(ARGS)

configure:
	xbuild /property:Configuration=Development /verbosity:quiet /nologo "$(UNREALROOTPATH)/Engine/Source/Programs/UnrealBuildTool/UnrealBuildTool.csproj"
	$(PROJECTBUILD) -projectfiles -project="\"$(GAMEPROJECTFILE)\"" -game -engine 

.PHONY: $(TARGETS)
